service:
  name: batch-system 

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

functions:
  batchSystem:
    handler: index.index
    events:
      - http:
          path: batch-system
          method: POST
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: CognitoAuthorizer
    role: arn:aws:iam::842652302289:role/lambda-iam

resources:
  Resources:
    AuditTableBatchSystem:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: AuditTableBatchSystem
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: stage
            AttributeType: S
          - AttributeName: msg
            AttributeType: S
          - AttributeName: url
            AttributeType: S
          - AttributeName: status
            AttributeType: S
          - AttributeName: errMsg
            AttributeType: S  
          - AttributeName: timeStored
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    
    CognitoAuthorizer:
      Type: 'AWS::ApiGateway::Authorizer'
      Properties:
        Name: batch-system-authorizer
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - arn-here